### ISSUE TITLE
Known Bugs | v4 BETA

### ISSUE THREAD

**Issue by Ephellon** [SpaceK33z/web-to-plex#58]
# TODO

- [x] fix the right-click bug
- [x] fix the empty requests bug
- [x] fix the VRV date bug
- [x] replace Flenix
- ~use Viduplayer for file downloads~
- [x] fix the options page (doesn't work with SSL served pages)
- [x] create the option to remove "Plex It" bookmarks
- [x] fix item saving bug
- [x] fix data saving/loading error
  - [x] added imdb, tmdb, and tvdb as "caching" sites

## "Right-Click Bug" - "Right-click | Find Title" event listeners (v1.2.0.0 - v3.1.2.0)

- When finding/opening an item, the listeners don't always fire (`/background.js::chrome.contextMenus.onClicked.addListener@anonymous`)

### Solution(s)

- Add a timer to `/background.js::chrome.contextMenus.onClicked.addListener@anonymous:if`
- __OR__ Add a fail-safe to `/background.js::chrome.contextMenus.onClicked.addListener@anonymous`
  - e.g. `if(new_window_not_open) refire_event;`

----

# "Empty Requests Bug"- Empty title queries (v0.0.0.0 - v3.1.2.0)

- Some scripts send empty queries even when the title isn't found

### Solution(s)

- [Add a fail-safe to `/utils.js::findPlexMedia`
  - e.g. `if(no_title || empty_title) throw title_error;`
- __OR__ Add a fail-safe to each site's script
  - e.g. `if(no_title || empty_title) throw title_error;`

----

# "VRV Date Bug" - VRV years vs. TVDb years

- VRV's series search year is sometimes off by more than 2 of The TVDb year
  - e.g. "Gundarr (1985 - TVDb)" v. "Gundarr (1990 - VRV)"

### Solution(s)

- Accept the first year found via the query
- __AND__<sup>?</sup> Force each query to be saved locally (MAX: 10)
  - i.e. if there are 8 different TV Shows by the name "Gundarr," save all of them in case one is matched later (via "right-click | find...," or other means)
- __OR__ Remove VRV altogether...

----

# Replace Flenix

### Solution(s)

- Use [GoStream](http://gostream.site/), which is some what "polished," and doesn't have as many annoying pop-ups

----

# Search for an HD MP4 file of a title

- After replacing Flenix, I noticed a streaming service always used: `viduplayer`, and turns out it's pretty straight forward

### Solution(s)

- Use the direct link first (for the right-click feature): `https://viduplayer.com/movies/{ IMDbID }_hd.mp4`

----

# Item Saving Bug

- The plugin would save empty (erroneous) data on empty replies

### Solution(s)

- Simply ignore the data and return before saving

# Data Loading/Saving Error

- The plugin would incorrectly save item data and render it useless across domains

### Solution(s)

- Completely rewrite the `load` and `save` functions as promises

**Comment by SpaceK33z** [comment]
Hi,

I merged your PR so we can continue from here. I began testing and changing some code a bit.

- I ran Prettier to make formatting more consistent.
- Support for Sonarr/Radarr and more with HTTPS was broken because you forcibly change https to http on [this line](https://github.com/SpaceK33z/web-to-plex/blob/d1c41b13304a440b3f963989f48ed783cbd8968f/src/options/index.js#L279). Fixed that by removing those lines.
- Sonarr/Radarr requests still fail after the above fix for me, even though it did work before all the changes. I think this might be because the options page runs in a separate tab now and cannot do requests without using CORS? I can research this further, but this is a blocker for me.
- I don't understand your usage of versions. The current extension is published as "v3.4", and after your changes it will be published as "v4.0".

**Comment by Ephellon** [comment]
*Please note changes have been made since the merge, so the lines won't match up!*

Hey @SpaceK33z , sorry about that; the next update should fix the issue: **if the user specifies HTTPS/HTTP, then use that mode, default to HTTP otherwise**.

- I changed the HTTP(S) request lines to `.replace(/^(?!^http(s)?:\/\/)(.+)/, 'http$1://$2')`
  - [/options/index.js:453](https://github.com/SpaceK33z/web-to-plex/blob/d1c41b13304a440b3f963989f48ed783cbd8968f/src/options/index.js#L453)
  - [/options/index.js:457](https://github.com/SpaceK33z/web-to-plex/blob/d1c41b13304a440b3f963989f48ed783cbd8968f/src/options/index.js#L457)
  - [/options/index.js:461](https://github.com/SpaceK33z/web-to-plex/blob/d1c41b13304a440b3f963989f48ed783cbd8968f/src/options/index.js#L461)
  - [/options/index.js:465](https://github.com/SpaceK33z/web-to-plex/blob/d1c41b13304a440b3f963989f48ed783cbd8968f/src/options/index.js#L465)

Sidenote: Tried to use Watcher with SSL enabled (HTTPS), but the new Chrome Update is no longer accepting the certificates.

**Comment by Ephellon** [comment]
Any other bugs?

**Comment by Ephellon** [comment]
Welp, Flenix will no longer be supported; but it did leave remnants for a similar feature:

### Search for an HD MP4 file of a title

`https://viduplayer.com/movies/{ IMDbID }_hd.mp4`

**Comment by SpaceK33z** [comment]
@Ephellon, Seems to be good so far. Very nice! However the fact that the options page is on a separate page now and as a result cannot access Radarr/Sonarr from HTTPS (with i.e. a reverse proxy) is a deal breaker for me. Perhaps we can add a separate background script for the options page that performs the requests? That might work.

**Comment by Ephellon** [comment]
Yes, that sounds like it might work

**Comment by Ephellon** [comment]
Alright, finally found some free time this week to work on WtP.

Alongside the fixes mentioned above, I'll add "create background script for options page."

@SpaceK33z, could you send me a (most recent) copy of the project so far, to keep things organised? I'll use the most recent merge for now.

**Comment by SpaceK33z** [comment]
Cool! Sorry for the radio silence on my part, been very busy. I haven't worked on it meanwhile, so this repository is up to date.

**Comment by Ephellon** [comment]
Same. I'll use this version then

**Comment by Ephellon** [comment]
Good evening/morning @SpaceK33z, I've made quite a few changes to the plugin (screenshot at bottom of post).

### Changes
- Replaced Flenix with GoStream (without file service)
- Sites no longer have a unique button location, instead it's a single location (the round button)
  - The button has a built-in "reload" feature (instead of always having to refresh the page if the plugin fails)
  - It also includes a button to activate the later-mentioned "Plex It!" feature
  - Also has an "open settings" button for easier settings access
  - Added new icons to reflect the above changes
- I've reused Plex's (deprecated) "Plex It!" feature as a bookmarking service (the left-hand panel)
  - _I was thinking about how I don't want to add a movie to Radarr sometimes_

### Help
- I still don't have access to a reverse proxy, so I haven't been able to test the new options page
  - I'm searching for SSL served managers online
  - if possible, could you send me logs/screenshots?

### More TODO
- [ ] Add the "remove" option for bookmarklets

### Screenshot (click to enlarge)
![image](https://user-images.githubusercontent.com/8632548/48393558-b7bf7300-e6d5-11e8-9475-ad217d09e5f8.png)

**Comment by Ephellon** [comment]
Hey @SpaceK33z, I just published v4 on [my channel](https://github.com/Ephellon/web-to-plex), please try it out and let me know of any errors you find.

**Comment by Ephellon** [comment]
v4.0 is ready to be reviewed: [Web to Plex (4.0.0.0) - Stable.zip](https://github.com/SpaceK33z/web-to-plex/files/2607293/Web.to.Plex.4.0.0.0.-.Stable.zip)

- Note: Radarr and Google's search page don't get along, I've tried to get them to play nice, but they really hate me. Radarr works perfectly on everything else. Sonarr and Watcher have no problem with Google's search page, just Radarr.

**Comment by SpaceK33z** [comment]
@Ephellon Cool. I liked the custom Plex buttons that have the same style as the rest of the site though, to be honest, but your new approach also has some advantages that I like. I tested the extension in Chrome.

* In the option page, I entered my Radarr details and when I click on "TEST", nothing happens at all.
* Same for Sonarr.
* Do Radarr/Sonarr work over https now (couldn't test it because of the two points above)? If not then that's the most important thing before releasing it as stable; we have a lot of users using that, including me.
* I don't understand why the "Plex It" button exists, you can do the same by using e.g. Pocket, bookmarks, or Letterboxd, IMDb or any other site you're already on.

**Comment by Ephellon** [comment]
Just fixed it, added the all_urls permission

**Comment by Ephellon** [comment]
Fixed with new permission: [Web to Plex (4.0.0.0).zip](https://github.com/SpaceK33z/web-to-plex/files/2612599/Web.to.Plex.4.0.0.0.zip)

**Comment by SpaceK33z** [comment]
Nice, tested again:

* Radarr works over https now, cool!
* I don't understand what the "Hide Web to Plex" button does?
* In the Sonarr and Radarr settings, the username/password fields need to be clarified; in my original extension it clearly says this is about [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication) and not about e.g. the username/password for Sonarr/Radarr itself.

**Comment by Ephellon** [comment]
The Hide button makes it transparent (on Netflix, etc) while it's unneeded.

I'll change those placeholders and descriptions.
